2019-02-19 15:04:38,822 ERROR: Exception on /addproblem [POST] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 258, in addproblem
    form.stdin.save(os.path.join(
AttributeError: 'FileField' object has no attribute 'save'
2019-02-19 15:05:05,333 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 15:05:38,638 ERROR: Exception on /addproblem [POST] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 258, in addproblem
    form.stdin.data.save(os.path.join(
AttributeError: 'str' object has no attribute 'save'
2019-02-19 15:13:08,339 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 18:32:35,336 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 18:41:09,391 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 18:41:18,814 ERROR: Exception on /addproblem [GET] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 250, in addproblem
    return render_template('addproblem.html', title='Add Problem', form=form)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\addproblem.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\base.html", line 63, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\addproblem.html", line 52, in block "app_content"
    {{ wtf.form_field(form.stdin) }}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 36, in template
    {% if field.flags.required and not required in kwargs %}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.AddProblem object' has no attribute 'stdin'
2019-02-19 18:41:52,627 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 18:43:54,226 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 18:45:58,782 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 19:00:00,277 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 19:01:37,216 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 19:02:16,889 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 19:09:59,366 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 19:11:35,956 ERROR: Exception on /update/11 [POST] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-02-19 19:12:47,759 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-19 19:26:37,372 ERROR: Exception on /commit/11 [POST] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 204, in commit
    record = Record.query.filter_by(problem_id=p.id,answer='accept',user_id=current_user.id).all()
NameError: name 'p' is not defined
2019-02-19 19:27:54,698 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:02:00,239 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
