2019-02-20 10:08:43,562 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:08:48,361 ERROR: Exception on /edit_inform/1 [GET] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 180, in edit_inform
    return render_template('edit_inform.html', title='Edit Inform', form=form)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\edit_inform.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\base.html", line 63, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\WuBingting\Desktop\newoj\app\templates\edit_inform.html", line 44, in block "app_content"
    {{ wtf.form_field(form.ms) }}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 36, in template
    {% if field.flags.required and not required in kwargs %}
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.AddInform object' has no attribute 'ms'
2019-02-20 10:09:55,821 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:10:56,870 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:14:56,492 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:15:00,043 ERROR: Exception on /edit_inform/1 [GET] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 179, in edit_inform
    return render_template('edit_inform.html', title='Edit Inform', form=form, content = infrom.content)
NameError: name 'infrom' is not defined
2019-02-20 10:15:26,116 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:17:06,552 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:20:49,858 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:21:28,765 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:22:06,880 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:25:38,612 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:27:38,302 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:29:58,609 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:30:27,259 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 10:35:22,154 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 12:21:15,602 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 12:21:50,182 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 12:38:14,052 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 12:38:27,620 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 12:45:18,872 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 12:45:20,519 ERROR: Exception on /addcontest [GET] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 81, in addcontest
    form.beg_time.data = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2019-02-20 12:45:46,792 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
2019-02-20 12:45:48,874 ERROR: Exception on /index [GET] [in c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\wubingting\desktop\newoj\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\WuBingting\Desktop\newoj\app\routes.py", line 382, in before_request
    current_user.last_seen = datetime.utcnow()
AttributeError: module 'datetime' has no attribute 'utcnow'
2019-02-20 12:47:15,050 INFO: OJ startup [in C:\Users\WuBingting\Desktop\newoj\app\__init__.py:34]
